/*
 * This source file was generated by the Gradle 'init' task
 */
package discord.bot;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.EnumSet;
import java.util.List;
import java.util.Scanner;

import javax.sql.DataSource;

import discord.bot.commands.DataBaseCommand;
import discord.bot.commands.MyCommand;
import discord.bot.commands.TimerCommand;
import discord.bot.commands.FlashcardCommand.FlashcardCommand;
import discord.bot.data.DataStore;
import discord.bot.managers.SlashCommandManager;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.JDABuilder;

import net.dv8tion.jda.api.requests.GatewayIntent;

public class App {
	public void setupBot() {
		String secret = getSecret();

		JDA api = JDABuilder.createDefault(secret)
				.enableIntents(EnumSet.allOf(GatewayIntent.class))
				.build();

		api.addEventListener(new MyListener());

		DataStore data = new DataStore();

		SlashCommandManager slashCommandManager = new SlashCommandManager();

		slashCommandManager.add(
				new MyCommand(),
				new TimerCommand(),
				new FlashcardCommand(),
				new DataBaseCommand());
		slashCommandManager.start(api, data);
	}

	final String fatalHeader = ("#").repeat(50);

	public void fatal(String message) {

		System.out.println(fatalHeader);
		System.out.println(" IMPORTANT <---");
		System.out.println(fatalHeader);
		System.out.println(message);
		System.out.println(fatalHeader);
		System.exit(1);
	}

	public String getSecret() {
		// System.out.println(System.getProperty("user.dir"));
		File secretFile = new File("../discord.token");

		String secret = null;

		try (Scanner reader = new Scanner(secretFile)) {
			if (!reader.hasNextLine()) {
				fatal("File called discord.token must contain 1 line with the Discord secret token.");
			}
			secret = reader.nextLine();
		} catch (FileNotFoundException e) {
			fatal(
					"Did not find secret!\nCreate a file discord.token in the root directory and paste your Discord bot token in it.");
		}

		System.out.println("Read discord bot token from file...");

		return secret;
	}

	public static void main(String[] args) {
		App app = new App();

		app.setupBot();
	}
}
